### ISSUE TITLE
关于intent.setFlags()的问题

### ISSUE THREAD

**Issue by luoxiaohui** [Xiasm/EasyRouter#6]
![image](https://user-images.githubusercontent.com/2830667/56258285-968a0500-6101-11e9-9940-2bfdeaaf7d37.png)
大佬，我写了测试代码:
`Intent intent = new Intent(mContext.getApplication().getApplicationContext(), TestActivity.class);
ActivityCompat.startActivity(mContext.getApplication().getApplicationContext(), intent, null);`
这样并不需要设置`FLAG_ACTIVITY_NEW_TASK`的启动模式，但也照样可以正常跳转。
图中箭头地方我比较困惑，为什么当currentContext为非Activity对象时，就需要设置`Intent.FLAG_ACTIVITY_NEW_TASK`?

**Comment by Jimmuy** [comment]
> ![image](https://user-images.githubusercontent.com/2830667/56258285-968a0500-6101-11e9-9940-2bfdeaaf7d37.png)
> 大佬，我写了测试代码:
> `Intent intent = new Intent(mContext.getApplication().getApplicationContext(), TestActivity.class); ActivityCompat.startActivity(mContext.getApplication().getApplicationContext(), intent, null);`
> 这样并不需要设置`FLAG_ACTIVITY_NEW_TASK`的启动模式，但也照样可以正常跳转。
> 图中箭头地方我比较困惑，为什么当currentContext为非Activity对象时，就需要设置`Intent.FLAG_ACTIVITY_NEW_TASK`?

因为在使用非Activity类型的context(例如application context)去startactivity的时候会抛异常，必须要加上这个flag

**Comment by luoxiaohui** [comment]
> > ![image](https://user-images.githubusercontent.com/2830667/56258285-968a0500-6101-11e9-9940-2bfdeaaf7d37.png)
> > 大佬，我写了测试代码:
> > `Intent intent = new Intent(mContext.getApplication().getApplicationContext(), TestActivity.class); ActivityCompat.startActivity(mContext.getApplication().getApplicationContext(), intent, null);`
> > 这样并不需要设置`FLAG_ACTIVITY_NEW_TASK`的启动模式，但也照样可以正常跳转。
> > 图中箭头地方我比较困惑，为什么当currentContext为非Activity对象时，就需要设置`Intent.FLAG_ACTIVITY_NEW_TASK`?
> 
> 因为在使用非Activity类型的context(例如application context)去startactivity的时候会抛异常，必须要加上这个flag

这个老哥，你没看我写的代码吗？

**Comment by luoxiaohui** [comment]
> > ![image](https://user-images.githubusercontent.com/2830667/56258285-968a0500-6101-11e9-9940-2bfdeaaf7d37.png)
> > 大佬，我写了测试代码:
> > `Intent intent = new Intent(mContext.getApplication().getApplicationContext(), TestActivity.class); ActivityCompat.startActivity(mContext.getApplication().getApplicationContext(), intent, null);`
> > 这样并不需要设置`FLAG_ACTIVITY_NEW_TASK`的启动模式，但也照样可以正常跳转。
> > 图中箭头地方我比较困惑，为什么当currentContext为非Activity对象时，就需要设置`Intent.FLAG_ACTIVITY_NEW_TASK`?
> 
> 因为在使用非Activity类型的context(例如application context)去startactivity的时候会抛异常，必须要加上这个flag

1. Application类型的context去startActivity，如果requestCode=-1的时候，是不会抛异常的！
2. 当requestCode!=-1的时候，此时的context必须是Activity类型的，所以在if(requestCode!=-1)逻辑中，就算intent设置了FLAG_ACTIVITY_NEW_TASK，也并没有什么用！
