### ISSUE TITLE
项目运行后无法跳转

### ISSUE THREAD

**Issue by Jimmuy** [Xiasm/EasyRouter#7]
断点提示：没有找到对应路由；
断点没有走到RouterProcessor里去，所以编译时没有生成routers。
暂时没找到原因，初次了解apt,可以给个提示吗，哪里出问题了，原项目没改动，手机是android 8.0系统

**Comment by luoxiaohui** [comment]
> 断点提示：没有找到对应路由；
> 断点没有走到RouterProcessor里去，所以编译时没有生成routers。
> 暂时没找到原因，初次了解apt,可以给个提示吗，哪里出问题了，原项目没改动，手机是android 8.0系统

删掉build文件夹，rebuild，我刚试了8.0系统是可以的。

**Comment by Jimmuy** [comment]
> > 断点提示：没有找到对应路由；
> > 断点没有走到RouterProcessor里去，所以编译时没有生成routers。
> > 暂时没找到原因，初次了解apt,可以给个提示吗，哪里出问题了，原项目没改动，手机是android 8.0系统
> 
> 删掉build文件夹，rebuild，我刚试了8.0系统是可以的。

试了不行，从始至终都没有生成过文件,代码拉下来也没有改动过
<img width="469" alt="image" src="https://user-images.githubusercontent.com/14874116/56800231-1ffdad80-684d-11e9-9b10-62183e81201d.png">
android studio 3.4

**Comment by luoxiaohui** [comment]
> > > 断点提示：没有找到对应路由；
> > > 断点没有走到RouterProcessor里去，所以编译时没有生成routers。
> > > 暂时没找到原因，初次了解apt,可以给个提示吗，哪里出问题了，原项目没改动，手机是android 8.0系统
> > 
> > 
> > 删掉build文件夹，rebuild，我刚试了8.0系统是可以的。
> 
> 试了不行，从始至终都没有生成过文件,代码拉下来也没有改动过
> <img alt="image" width="469" src="https://user-images.githubusercontent.com/14874116/56800231-1ffdad80-684d-11e9-9b10-62183e81201d.png">
> android studio 3.4

应该就是studio版本的问题，我之前3.3.2没问题，刚升级到3.4，也没法自动生成代码了，这个可以研究下～作者写这个路由，里面思想还是挺清晰的，建议退到3.3.2或以下，先把代码跑起来，看看原理。

**Comment by Jimmuy** [comment]
> > > > 断点提示：没有找到对应路由；
> > > > 断点没有走到RouterProcessor里去，所以编译时没有生成routers。
> > > > 暂时没找到原因，初次了解apt,可以给个提示吗，哪里出问题了，原项目没改动，手机是android 8.0系统
> > > 
> > > 
> > > 删掉build文件夹，rebuild，我刚试了8.0系统是可以的。
> > 
> > 
> > 试了不行，从始至终都没有生成过文件,代码拉下来也没有改动过
> > <img alt="image" width="469" src="https://user-images.githubusercontent.com/14874116/56800231-1ffdad80-684d-11e9-9b10-62183e81201d.png">
> > android studio 3.4
> 
> 应该就是studio版本的问题，我之前3.3.2没问题，刚升级到3.4，也没法自动生成代码了，这个可以研究下～作者写这个路由，里面思想还是挺清晰的，建议退到3.3.2或以下，先把代码跑起来，看看原理。

好的，非常感谢

**Comment by Jimmuy** [comment]
升级 as 3.4的同学 将根项目的build.gradle设置为如图
![image](https://user-images.githubusercontent.com/14874116/56860100-257e0380-69c5-11e9-8f4a-55e4ece3fbed.png)
将gradle-wrapper.properties设置成
![image](https://user-images.githubusercontent.com/14874116/56860117-62e29100-69c5-11e9-8b66-328b526850ad.png)
clean rebuild 后方可解决

**Comment by luoxiaohui** [comment]
> 升级 as 3.4的同学 将根项目的build.gradle设置为如图
> ![image](https://user-images.githubusercontent.com/14874116/56860100-257e0380-69c5-11e9-8f4a-55e4ece3fbed.png)
> 将gradle-wrapper.properties设置成
> ![image](https://user-images.githubusercontent.com/14874116/56860117-62e29100-69c5-11e9-8b66-328b526850ad.png)
> clean rebuild 后方可解决

gradle升级到5.0之后，对auto-service有影响，之前的注解方式实现不了了，需要在easy-compiler模块的build.gradle文件中添加依赖:
`annotationProcessor 'com.google.auto.service:auto-service:1.0-rc2'`
亲测，可用！
具体解释参照https://github.com/gradle/gradle/issues/7941
